### ISSUE TITLE
Got a google notifications it contains malware. Why did you delete the issue? 

### ISSUE THREAD

**Issue by kapicaluk** [rbrahul/Awesome-JSON-Viewer#64]
![image](https://user-images.githubusercontent.com/12704783/97025965-9e541200-150d-11eb-8f75-337c80bc1bb3.png)

**Comment by lagofvc** [comment]
+1

**Comment by rbrahul** [comment]
Dear beautiful People, 
[JSON Viewer Pro](https://chrome.google.com/webstore/detail/json-viewer-pro/eifflpmocdbdmepbjaopkkhbfmdgijcc) is not **JSON Viewer Awesome** , it's a completely separate extension with same feature set which will be regularly maintained. It's completely free and in no circumstances will contain any advertisements or monetization. I have so many friends who used to use  **JSON Viewer Awesome** everyday even personally me as well. That's why I released **JSON Viewer Pro** .
If you like you can get it from Chrome Extension store. Here is the URL:

[https://chrome.google.com/webstore/detail/json-viewer-pro/eifflpmocdbdmepbjaopkkhbfmdgijcc](https://chrome.google.com/webstore/detail/json-viewer-pro/eifflpmocdbdmepbjaopkkhbfmdgijcc)

**And another important NOTE:**  When the ownership of **JSON Viewer Awesome** was changed, on the same day I posted in my **[https://github.com/rbrahul/Awesome-JSON-Viewer/](https://github.com/rbrahul/Awesome-JSON-Viewer/)** repository in the main README file describing as follows:

 ### ⚠️ IMPORTANT!!! JSON Viewer Awesome is no longer owned, maintained and developed by me or from this repository. The ownership of this JSON Viewer Awesome was changed

**Comment by rbrahul** [comment]
@kapicaluk I think you found this screenshot in any archive or somewhere else which does not contains some of my comments. I pretty much described everything that I did not add any script which could be malicious and the ownership was changed a few months ago. What I think that the owner might have implemented **monetization** which could lead to advertisements. If lot of users complains about these then it could have been banned.
And the issue you mentioned which was deleted by me, there were some people who are pulling the conversation in different direction and I was personally offended what guided me to delete the issue. I hope it helped to clear you confusion. Thanks.

**Comment by bhrd** [comment]
@rbrahul [Your detailed comment](https://github.com/rbrahul/Awesome-JSON-Viewer/issues/64#issuecomment-715529497) above still doesn't explain **why Chrome issued the warning** that the original extension contains malware. Can you provide some insight into that?

According to [this commit](https://github.com/rbrahul/Awesome-JSON-Viewer/commit/56a8e542638248a1fb8d57b48cf3d99592dd6998#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5), you were the owner of the infected extension **JSON Viewer Awesome** as well and looks like the repo was updated to become the new **JSON Viewer Pro**. 
It would be nice to know why this extension was flagged by Chrome.
Thanks!

**Comment by rbrahul** [comment]
@bhrd **JSON viewer Awesome** was developed by me and I was the previous owner. It was published initially in my Google Chrome Store Account. The ownership of the chrome extension store was transferred to another person, but the Github repo still exists. The owner released new versions what I have noticed. He might have violated Google Chrome Store user privacy policy. I can't tell you the exact reason because neither I was the owner of that Chrome Extension nor Google Chrome Extension team communicated to me.

Since I was using that extension everyday, I needed it to be live. That's why I released **JSON viewer PRO** for my personal use and for my friends after **JSON viewer Awesome** getting banned. 
Thanks
